### ISSUE TITLE
Header file missing

### ISSUE THREAD

**Issue by miroljubst** [leoneparise/GoogleMaps-Carthage#11]
GMSPolygonLayer.h missing in xcode project also in  Build phases/headers

**Comment by leoneparise** [comment]
Can you open a PR?

**Comment by miroljubst** [comment]
Opened PR

**Comment by petrovi4** [comment]
+1, same issue

**Comment by leoneparise** [comment]
@miroljubst merged. @petrovi4 I just pushed a new tag. Please, try again.
