### ISSUE TITLE
New version of Google Maps SDK for iOS

### ISSUE THREAD

**Issue by petrovi4** [leoneparise/GoogleMaps-Carthage#14]
As I see in XCode Debug Area, new version of Google Maps SDK was released:

> New version of Google Maps SDK for iOS (M4B) and Google Places API for iOS available: 3.1.206.0

Can you please update your repo? Thanks!

Pull request already ready https://github.com/leoneparise/GoogleMaps-Carthage/pull/13

**Comment by leoneparise** [comment]
Hey, I just updated the repo and added `3.1.0` tag.
