### ISSUE TITLE
Carthage outdated run script build fail

### ISSUE THREAD

**Issue by norbdev** [leoneparise/GoogleMaps-Carthage#16]
If I add this run script:
/usr/local/bin/carthage outdated --xcode-warnings

The build failed with this:

A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/leoneparise/GoogleMaps-Carthage.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/norb/Library/Caches/org.carthage.CarthageKit/dependencies/GoogleMaps-Carthage)) failed with exit code 1

Xcode 11, Carthage 0.33.0

**Comment by dhara6894** [comment]
*** Checking out GoogleMaps-Carthage at "2.7.0"
A shell task (/usr/bin/env git checkout --quiet --force 2.7.0 (launched in /Users/dharapatel/Library/Caches/org.carthage.CarthageKit/dependencies/GoogleMaps-Carthage)) failed with exit code 128:
fatal: Unable to create '/Users/dharapatel/Library/Caches/org.carthage.CarthageKit/dependencies/GoogleMaps-Carthage/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**Comment by leoneparise** [comment]
I just updated to 3.3.0. Can you check again?

**Comment by norbdev** [comment]
The error the same.

In the Cartfile tried both:
github "leoneparise/GoogleMaps-Carthage" "3.3.0"
github "leoneparise/GoogleMaps-Carthage" == 3.3.0

carthage outdated

A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/leoneparise/GoogleMaps-Carthage.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/norb/Library/Caches/org.carthage.CarthageKit/dependencies/GoogleMaps-Carthage)) failed with exit code 1

**Comment by norbdev** [comment]
with 3.3.1 the error is gone
