### ISSUE TITLE
Carthage GoogleMaps-Carthage update issue  

### ISSUE THREAD

**Issue by dhara6894** [leoneparise/GoogleMaps-Carthage#17]
*** Checking out GoogleMaps-Carthage at "2.7.0"
A shell task (/usr/bin/env git checkout --quiet --force 2.7.0 (launched in /Users/dharapatel/Library/Caches/org.carthage.CarthageKit/dependencies/GoogleMaps-Carthage)) failed with exit code 128:
fatal: Unable to create '/Users/dharapatel/Library/Caches/org.carthage.CarthageKit/dependencies/GoogleMaps-Carthage/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**Comment by leoneparise** [comment]
I just updated to 3.3.0. Can you check again?

**Comment by umerafzal** [comment]
A shell task (/usr/bin/env git checkout --quiet --force 3.3.1 (launched in /Users/umafzal/Library/Caches/org.carthage.CarthageKit/dependencies/GoogleMaps-Carthage)) failed with exit code 128:
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly

I am facing this issue while running `carthage update --platform iOS` command.
Carthage version: 0.35.0
Git Version: 2.19.1
which Git: /usr/local/bin/git

I have tried these links but could not be able to resolve this issue [642](https://github.com/Carthage/Carthage/issues/642) , [694](https://github.com/Carthage/Carthage/issues/694)

Can you guide me how can I resolve this issue? Thanks

P.S. : This is my first question on Github. Apologies if I didn't follow the proper guidelines on how to report an issue.
