### ISSUE TITLE
Error 3.3.0

### ISSUE THREAD

**Issue by alekzernov** [leoneparise/GoogleMaps-Carthage#18]
In version 3.3.0 I get an error at the time of compiling 'GMSStrokeStyle.h' file not found

**Comment by alekzernov** [comment]
Another question is what version of google places in this sdk?

**Comment by michael-mckenna** [comment]
Getting this issue too

**Comment by meyusufdemirci** [comment]
[GMSStrokeStyle.h.zip](https://github.com/leoneparise/GoogleMaps-Carthage/files/4069785/GMSStrokeStyle.h.zip)

Here is the file. Extract it and paste it to Carthage/Build/iOS/GoogleMaps.framework/Headers

**Comment by leoneparise** [comment]
Just updated the release, please try again.
