### ISSUE TITLE
GMSStrokeStyles Missing

### ISSUE THREAD

**Issue by mmr118** [leoneparise/GoogleMaps-Carthage#19]
`GMSStrokeStyles.h` is in the directory but not included in project.

**Comment by mmr118** [comment]
@leoneparise May I be added as a contributor so I can submit a pull request?

**Comment by paymand** [comment]
@leoneparise Created a PR with the fix for this issue here: https://github.com/leoneparise/GoogleMaps-Carthage/pull/20

Please take a look 😄

**Comment by darakpanand** [comment]
@paymand any approximate time when this issue will get closed?

**Comment by paymand** [comment]
@darakpanand I don't have write access to the repo, so I cannot merge the PR.
It's up to @leoneparise to merge.

**Comment by darakpanand** [comment]
Thanks @paymand for the update. @leoneparise I tried this fix locally but it didn't work. I have tried direct binary injection from https://dl.google.com/dl/cpdc/f5a3789e77faee18/GoogleMaps-3.7.0.tar.gz which has worked and resolved the given issue.

**Comment by paymand** [comment]
@darakpanand You're totally correct.
I had forgotten to include the header in public headers.
@leoneparise The release 3.3.0 is still missing the header. I've made a fix here: https://github.com/leoneparise/GoogleMaps-Carthage/pull/21
Could you please merge and make a 3.3.1 release?
