### ISSUE TITLE
Update to 2.7.x

### ISSUE THREAD

**Issue by jaymehtasa** [leoneparise/GoogleMaps-Carthage#7]
Can you update to latest version?

**Comment by johndelong** [comment]
I've updated to 2.7 in [this pr](https://github.com/leoneparise/GoogleMaps-Carthage/pull/8)

**Comment by oliver-was-here** [comment]
@leoneparise when you get a chance can you tag 5546255eac4b20eb5600fc6e98ae7d0320efb5e5 as `2.7.0`?

**Comment by leoneparise** [comment]
Done @oliver-was-here!

**Comment by leoneparise** [comment]
I'm closing this issue.
